spring.application.name=ai-image-enhancer

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_enhancer_db
spring.datasource.username=postgres
spring.datasource.password=sanu1913

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

replicate.api.url=https://api.replicate.com/v1
replicate.api.token=${REPLICATE_API_TOKEN}


